# Generated by Django 3.1.4 on 2020-12-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='developmentinf',
            name='top_image',
            field=models.ImageField(blank=True, help_text='top image to be listed to home', null=True, upload_to='images/DevelopmentInf', verbose_name='top_image'),
        ),
    ]
