# Generated by Django 3.1.4 on 2020-12-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_developmentinf_top_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developmentinf',
            name='links',
            field=models.ManyToManyField(blank=True, related_name='links', to='models.LinkInf'),
        ),
        migrations.AlterField(
            model_name='linkinf',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/DeveloperInf'),
        ),
    ]
