# Generated by Django 3.1.4 on 2020-12-31 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201230_0241'),
        ('models', '0003_auto_20201230_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developmentinf',
            name='associations',
            field=models.ManyToManyField(blank=True, related_name='developmentinf_associations', to='users.Association'),
        ),
        migrations.AlterField(
            model_name='developmentinf',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
