# Generated by Django 3.1.1 on 2020-09-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoryInf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryid', models.IntegerField()),
                ('categoryname', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='developerInf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developerid', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/developerInf')),
            ],
        ),
        migrations.CreateModel(
            name='developPartInf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developerid', models.IntegerField()),
                ('developername', models.TextField()),
                ('generation', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='downloadLinkInf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameid', models.IntegerField()),
                ('machineid', models.IntegerField()),
                ('link', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GameCategoryInf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameid', models.IntegerField()),
                ('categoryid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='gameInf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameid', models.IntegerField()),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('userid', models.IntegerField()),
                ('status', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/gameInf')),
                ('submittedtime', models.DateTimeField()),
                ('updatedtime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='gameScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameid', models.IntegerField()),
                ('player', models.TextField()),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='machineInf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machineid', models.IntegerField()),
                ('machinename', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='statusInf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusid', models.IntegerField()),
                ('statusname', models.TextField()),
            ],
        ),
    ]
