# Generated by Django 3.0.7 on 2020-08-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gameInf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameid', models.IntegerField()),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('userid', models.IntegerField()),
                ('status', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/gameInf')),
                ('submittedtime', models.DateTimeField()),
                ('updatedtime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='gameScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameid', models.IntegerField()),
                ('player', models.TextField()),
                ('score', models.IntegerField()),
            ],
        ),
    ]
