# Generated by Django 3.1.2 on 2020-10-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='developpartinf',
            name='gameid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='developpartinf',
            name='partinf',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoryinf',
            name='categoryid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='downloadlinkinf',
            name='gameid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='downloadlinkinf',
            name='machineid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamecategoryinf',
            name='categoryid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamecategoryinf',
            name='gameid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gameinf',
            name='gameid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamescore',
            name='gameid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamescore',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='machineinf',
            name='machineid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statusinf',
            name='statusid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
