# Generated by Django 3.0.7 on 2020-08-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoryInf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryid', models.IntegerField()),
                ('categoryname', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='developerInf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developerid', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/developerInf')),
            ],
        ),
        migrations.CreateModel(
            name='developPartInf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developerid', models.IntegerField()),
                ('developername', models.TextField()),
                ('generation', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='downloadLinkInf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameid', models.IntegerField()),
                ('machineid', models.IntegerField()),
                ('link', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GameCategoryInf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameid', models.IntegerField()),
                ('categoryid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='machineInf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machineid', models.IntegerField()),
                ('machinename', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='statusInf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusid', models.IntegerField()),
                ('statusname', models.TextField()),
            ],
        ),
    ]
