# Generated by Django 3.1.2 on 2020-10-06 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0002_auto_20201007_0108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameinf',
            options={'verbose_name_plural': 'gameInf'},
        ),
    ]
