# Generated by Django 3.1.1 on 2020-09-15 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0002_categoryinf_developerinf_developpartinf_downloadlinkinf_gamecategoryinf_machineinf_statusinf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='developerinf',
            old_name='developerid',
            new_name='gameid',
        ),
    ]
