# Generated by Django 3.1.1 on 2020-10-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0003_auto_20201007_0119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryinf',
            options={'verbose_name_plural': 'CategoryInf'},
        ),
        migrations.AlterModelOptions(
            name='developerinf',
            options={'verbose_name_plural': 'DeveloperInf'},
        ),
        migrations.AlterModelOptions(
            name='developpartinf',
            options={'verbose_name_plural': 'DevelopPartInf'},
        ),
        migrations.AlterModelOptions(
            name='downloadlinkinf',
            options={'verbose_name_plural': 'DownloadLinkInf'},
        ),
        migrations.AlterModelOptions(
            name='gamecategoryinf',
            options={'verbose_name_plural': 'GameCategoryInf'},
        ),
        migrations.AlterModelOptions(
            name='gameinf',
            options={'verbose_name_plural': 'GameInf'},
        ),
        migrations.AlterModelOptions(
            name='gamescore',
            options={'verbose_name_plural': 'GameScore'},
        ),
        migrations.AlterModelOptions(
            name='machineinf',
            options={'verbose_name_plural': 'MachineInf'},
        ),
        migrations.AlterModelOptions(
            name='statusinf',
            options={'verbose_name_plural': 'StatusInf'},
        ),
        migrations.AlterField(
            model_name='gameinf',
            name='image',
            field=models.ImageField(upload_to='images/GameInf'),
        ),
    ]
