# Generated by Django 3.1.1 on 2020-09-15 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0003_auto_20200915_2308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='developerinf',
            old_name='gameid',
            new_name='developerid',
        ),
    ]
