# Generated by Django 3.1.1 on 2020-11-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0009_auto_20201106_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinf',
            name='status',
            field=models.IntegerField(),
        ),
    ]
