version: '3'

services: 
    web:
        build: ./
        container_name: misw-meseum_web
        command: python manage.py runserver 0.0.0.0:8000
        volumes: 
            - ./:/app/
        ports: 
            - 8000:8000
        environment: 
            - DATABASE_ENGINE=django.db.backends.postgresql
            - DATABASE_DB=django_db
            - DATABASE_USER=root
            - DATABASE_PASSWORD=password
            - DATABASE_HOST=db
            - DATABASE_PORT=5432
        env_file: ./.env
        depends_on: 
            - db
    
    db:
        image: postgres:12
        container_name: misw-meseum_db
        volumes: 
            - dbdata:/var/lib/postgresql/dbdata
        environment: 
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=django_db


volumes: 
    dbdata:
        driver: local