version: '3'

services: 
    web:
        build: ./
        command: python manage.py runserver 0.0.0.0:8000
        volumes: 
            - ./:/usr/src/app/
        ports: 
            - 8000:8000
        environment: 
            #- SECRET_KEY=...
            - DATABASE_ENGINE=django.db.backends.postgresql
            - DATABASE_DB=django_db
            - DATABASE_USER=django_db_user
            - DATABASE_PASSWORD=django_db_password
            - DATABASE_HOST=db
            - DATABASE_PORT=5432
        depends_on: 
            - db
    
    db:
        image: postgres:12
        volumes: 
            - postgres_data:/var/lib/postgresql/data
        environment: 
            - POSTGRES_USER=django_db_user
            - POSTGRES_PASSWORD=django_db_password
            - POSTGRES_DB=django_db


volumes: 
    postgres_data: