# Generated by Django 3.1.1 on 2020-11-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0007_auto_20201007_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinf',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/GameInf'),
        ),
    ]
