# Generated by Django 3.1.1 on 2020-11-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0008_auto_20201106_0247'),
    ]

    operations = [
        migrations.DeleteModel(
            name='categoryInf',
        ),
        migrations.DeleteModel(
            name='downloadLinkInf',
        ),
        migrations.DeleteModel(
            name='GameCategoryInf',
        ),
        migrations.DeleteModel(
            name='machineInf',
        ),
        migrations.DeleteModel(
            name='statusInf',
        ),
        migrations.AddField(
            model_name='gameinf',
            name='categoryid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameinf',
            name='categoryname',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gameinf',
            name='status',
            field=models.BooleanField(default=False, help_text='false: not publish, true: publish.'),
        ),
    ]
