# Generated by Django 3.1.1 on 2020-09-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='generation',
            field=models.IntegerField(blank=True, help_text='Specific Generation for this user.', verbose_name='generation'),
        ),
    ]
