# Generated by Django 3.1.1 on 2020-09-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200919_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='generation',
            field=models.CharField(blank=True, help_text='Specific Generation for this user.', max_length=150, verbose_name='generation'),
        ),
    ]
