# Generated by Django 3.1.4 on 2021-01-29 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('type', models.IntegerField(choices=[(1, 'Windows'), (2, 'iOS'), (3, 'Android'), (4, 'ブラウザ'), (5, 'その他')], help_text='1: Windows, 2: iOS, 3: Android, 4: browser, 5: others')),
                ('link', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Link',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('type', models.IntegerField(choices=[(1, '画像'), (2, '音声'), (3, '動画')], help_text='1: image, 2: sound, 3: video')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/Development')),
            ],
        ),
        migrations.CreateModel(
            name='Development',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('status', models.IntegerField(default=0, help_text='0: 申請中, 1: 公開中, 2: 非公開', verbose_name='status')),
                ('is_private', models.BooleanField(default=False, help_text='Open only within misw or not')),
                ('top_image', models.ImageField(blank=True, help_text='top image to be listed to home', null=True, upload_to='images/Development', verbose_name='top_image')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('associations', models.ManyToManyField(blank=True, related_name='development_associations', to='users.Association')),
                ('links', models.ManyToManyField(related_name='links', to='developments.Link')),
                ('medias', models.ManyToManyField(related_name='Medias', to='developments.Media')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='development_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('users', models.ManyToManyField(related_name='development_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Development',
            },
        ),
    ]
