# Generated by Django 3.1.7 on 2021-03-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='type',
            field=models.IntegerField(choices=[(0, 'Microsoft Store'), (1, 'Apple Store'), (2, 'Google Play'), (3, 'その他')], help_text='0: Windows, 1: iOS, 2: Android, 3: browser, 4: others'),
        ),
    ]
