# Generated by Django 3.2.9 on 2021-11-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='type',
            field=models.IntegerField(choices=[(0, 'Microsoft Store'), (1, 'Apple Store'), (2, 'Google Play'), (3, 'Browser'), (4, 'Others')]),
        ),
    ]
