# Generated by Django 3.1.4 on 2021-01-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='development',
            name='status',
            field=models.IntegerField(choices=[(0, '申請中'), (1, '公開中'), (2, '非公開')], default=0, help_text='0: 申請中, 1: 公開中, 2: 非公開', verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='link',
            name='type',
            field=models.IntegerField(choices=[(0, 'Windows'), (1, 'iOS'), (2, 'Android'), (3, 'ブラウザ'), (4, 'その他')], help_text='1: Windows, 2: iOS, 3: Android, 4: browser, 5: others'),
        ),
        migrations.AlterField(
            model_name='media',
            name='type',
            field=models.IntegerField(choices=[(0, '画像'), (1, '音声'), (2, '動画')], help_text='1: image, 2: sound, 3: video'),
        ),
    ]
