# Generated by Django 3.1.4 on 2021-01-29 10:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('developments', '0003_auto_20210129_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='development',
            name='links',
            field=models.ManyToManyField(blank=True, related_name='links', to='developments.Link'),
        ),
        migrations.AlterField(
            model_name='development',
            name='medias',
            field=models.ManyToManyField(blank=True, related_name='Medias', to='developments.Media'),
        ),
        migrations.AlterField(
            model_name='development',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='development_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
