# Generated by Django 3.1.5 on 2021-01-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, default='', help_text="User's description. Editable.", null=True, verbose_name='description'),
        ),
    ]
