# Generated by Django 3.1.4 on 2020-12-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, help_text="User's description. Editable.", null=True, verbose_name='description'),
        ),
    ]
