# Generated by Django 3.1.5 on 2021-01-31 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210130_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(0, 'admin'), (1, 'member')], default=1, help_text='0: admin, 1: member', verbose_name='role'),
        ),
    ]
