# Generated by Django 3.1.4 on 2021-01-29 13:23

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210129_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='associations',
            field=models.CharField(blank=True, default='', help_text='0: programming, 1: CG, 2: MIDI', max_length=6, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='associations'),
        ),
    ]
