# Generated by Django 3.1.4 on 2020-12-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201230_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='associations',
            field=models.ManyToManyField(blank=True, related_name='associations', to='users.Association'),
        ),
    ]
