# Generated by Django 3.1.5 on 2021-01-31 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, default='', help_text="User's description. Editable.", verbose_name='description'),
        ),
    ]
